### PR TITLE
Feat: add support for custom context snippets

### PR DESCRIPTION
**Pull request by smjonas**
For example the snippet `frac`
```snippets
global !p
def math():
    return vim.eval('vimtex#syntax#in_mathzone()') == '1'
endglobal

context "math()"
snippet frac "Fraction"
\\frac{$1}{$2}$0
endsnippet
```
will now be shown by cmp when the user is in math mode in a `.tex` file.

### CODE REVIEW

**Review by quangnguyen30192 — APPROVED** [review]

**Review by quangnguyen30192 — APPROVED** [review]

**Comment by smjonas** [comment]
@quangnguyen30192 @jasonkena could one of you quickly test this branch? I tested it better myself this time and it seems to be working fine but I just want to be sure before merging :)

**Comment by quangnguyen30192** [comment]
How do I test it 😅 could you provide me the steps?

**Comment by quangnguyen30192** [comment]
Thanks, tested, LGTM

**Comment by jasonkena** [comment]
@smjonas thank you for your work! Unfortunately, the expansions are also work outside the math contexts, the "iA" (auto-trigger) flags on the snippets do not work, and complex pattern matching fails e.g.
```
context "math()"
snippet "([a-zA-Z])hat" "hat" riA
\hat{`!p snip.rv=match.group(1)`}
endsnippet
```

**Comment by smjonas** [comment]
Thank you for the feedback, I will check it!

**Comment by jasonkena** [comment]
@smjonas hmm... it's still broken for me. Could you please send a minimal vimrc/luarc?

**Pull request merged**
