### PR TITLE
Feat: add composable mappings, e.g. use a separate key to jump between snippet tabstops

### PR DESCRIPTION
**Pull request by smjonas**
- add "actions" users can use to compose their own mappings
- update readme

### CODE REVIEW

**Comment by smjonas** [comment]
@mathjiajia could you please test this PR and confirm that everything works as expected? :)

**Review by quangnguyen30192 — APPROVED** [review]

**Comment by smjonas** [comment]
I'll wait for @mathjiajia before merging, then I will squash

**Comment by mathjiajia** [comment]
Dear @smjonas, thanks so much.
I tested this PR a bit and it works well.

BTW, if you want to add some explanation in README, below may be better?
Since for those who does not `Tab` to jump forward, they will not use `S-Tab` to jump back.
How do you think?

```
["<Tab>"] = cmp.mapping(
          function(fallback)
            cmp_ultisnips_mappings.expand_or_jump_forwards(fallback)
            -- Alternatively, if you prefer a separate key for jumping between snippet tabstops:
            -- cmp_ultisnips_mappings.expand(fallback)
          end,
          {
            "i", "s",
            -- add this line when using cmp-cmdline:
            -- "c",
          }
        ),
["<S-Tab>"] = cmp.mapping(
          function(fallback)
            cmp_ultisnips_mappings.jump_backwards(fallback)
            -- Alternatively, if you prefer a separate key for jumping between snippet tabstops:
            -- if cmp.visible() then
            --   cmp.select_prev_item()
            -- else
            --   fallback()
            -- end
          end,
          {
            "i", "s",
            -- add this line when using cmp-cmdline:
            -- "c",
          }
        ),
```

**Comment by smjonas** [comment]
Thanks for the testing it! I just had another idea how to handle this problem: we could
make the mappings "composable": what I mean is we can provide the basic functions `expand`, `jump-forwards`, `jump_backwards`, `select_next`, `select_prev`. We can still keep the defaults as they are now in the readme. Then users can define which of them they want to use in a specific order by passing a table. And we can still provide a default example in the readme. What do you think?

**Comment by quangnguyen30192** [comment]
Sounds good to me 💪

**Comment by smjonas** [comment]
Unrelated: do you guys still see `=UltiSnips#ExpandSnippet()` in the command line when pressing tab? That was supposed to be fixed already but I just saw it again...

**Comment by quangnguyen30192** [comment]
it still persists yeah

**Comment by smjonas** [comment]
But it only happens when nothing is selected, right? Like at the beginning of a line?

**Comment by mathjiajia** [comment]
Thanks to both of you.
The "composable" mapping idea is great.

BTW, `=UltiSnips#ExpandSnippet()` disappears in my computer since this PR #42.

**Comment by smjonas** [comment]
Btw I didnt't forget about this PR, just thought it was fun to work on treesitter integration for a bit ;) (see #50)

**Review by quangnguyen30192 — APPROVED** [review]
Looks pretty good

**Review by quangnguyen30192 — APPROVED** [review]

**Comment by smjonas** [comment]
Thanks

**Pull request merged**
