### PR TITLE
[WIP] Feat: move recommended mappings to a dedicated module

### PR DESCRIPTION
**Pull request by smjonas**
TODO:
- [X] create separate config and mappings modules
- [X] call functions silently using `<Plug>` mappings. [Solved](https://github.com/hrsh7th/nvim-cmp/discussions/616) with the help of hrsh7th!
- [X] update readme

### CODE REVIEW

**Comment by smjonas** [comment]
@quangnguyen30192 hope it's okay that I have removed the `C-space` mapping. I think not many users would use it (also they can just use cmp's default `cmp.complete()` mapping).

**Comment by quangnguyen30192** [comment]
@smjonas sure 👍  I'm ok with that

**Review by quangnguyen30192 — APPROVED** [review]
Nice one 👍

**Comment by smjonas** [comment]
Thanks! I hope this will solve all current mapping related issues! :) Also we can change the implementation easier without the users having to update their config.

**Comment by quangnguyen30192** [comment]
> Thanks! I hope this will solve all current mapping related issues!

Definitely, it does, thanks for making it great

**Pull request merged**
